/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js}'],
  theme: {
    extend: {
      colors: {
        // ─── Ana Renk Değişkenleri ───────────────────────────────────────
        // Bu değerleri değiştirerek sitenin tüm renklerini güncelleyebilirsiniz.
        // CSS custom properties ile de kontrol edilebilir: src/styles/variables.css
        'primary':                    'var(--color-primary)',
        'primary-container':          'var(--color-primary-container)',
        'on-primary':                 'var(--color-on-primary)',
        'on-primary-container':       'var(--color-on-primary-container)',
        'on-primary-fixed':           'var(--color-on-primary-fixed)',
        'on-primary-fixed-variant':   'var(--color-on-primary-fixed-variant)',
        'primary-fixed':              'var(--color-primary-fixed)',
        'primary-fixed-dim':          'var(--color-primary-fixed-dim)',
        'inverse-primary':            'var(--color-inverse-primary)',

        'secondary':                  'var(--color-secondary)',
        'secondary-container':        'var(--color-secondary-container)',
        'on-secondary':               'var(--color-on-secondary)',
        'on-secondary-container':     'var(--color-on-secondary-container)',
        'secondary-fixed':            'var(--color-secondary-fixed)',
        'secondary-fixed-dim':        'var(--color-secondary-fixed-dim)',
        'on-secondary-fixed':         'var(--color-on-secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',

        'tertiary':                   'var(--color-tertiary)',
        'tertiary-container':         'var(--color-tertiary-container)',
        'on-tertiary':                'var(--color-on-tertiary)',
        'on-tertiary-container':      'var(--color-on-tertiary-container)',
        'tertiary-fixed':             'var(--color-tertiary-fixed)',
        'tertiary-fixed-dim':         'var(--color-tertiary-fixed-dim)',
        'on-tertiary-fixed':          'var(--color-on-tertiary-fixed)',
        'on-tertiary-fixed-variant':  'var(--color-on-tertiary-fixed-variant)',

        'error':                      'var(--color-error)',
        'error-container':            'var(--color-error-container)',
        'on-error':                   'var(--color-on-error)',
        'on-error-container':         'var(--color-on-error-container)',

        'background':                 'var(--color-background)',
        'on-background':              'var(--color-on-background)',
        'surface':                    'var(--color-surface)',
        'on-surface':                 'var(--color-on-surface)',
        'surface-variant':            'var(--color-surface-variant)',
        'on-surface-variant':         'var(--color-on-surface-variant)',
        'inverse-surface':            'var(--color-inverse-surface)',
        'inverse-on-surface':         'var(--color-inverse-on-surface)',
        'surface-tint':               'var(--color-surface-tint)',
        'surface-dim':                'var(--color-surface-dim)',
        'surface-bright':             'var(--color-surface-bright)',
        'surface-container-lowest':   'var(--color-surface-container-lowest)',
        'surface-container-low':      'var(--color-surface-container-low)',
        'surface-container':          'var(--color-surface-container)',
        'surface-container-high':     'var(--color-surface-container-high)',
        'surface-container-highest':  'var(--color-surface-container-highest)',
        'surface-obsidian':           'var(--color-surface-obsidian)',
        'surface-charcoal':           'var(--color-surface-charcoal)',
        'surface-raised':             'var(--color-surface-raised)',

        'outline':                    'var(--color-outline)',
        'outline-variant':            'var(--color-outline-variant)',
        'border-subtle':              'var(--color-border-subtle)',
        'text-primary':               'var(--color-text-primary)',
        'text-secondary':             'var(--color-text-secondary)',
        'glow-red':                   'var(--color-glow)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-mobile': '16px',
        'stack-lg': '32px',
        'stack-md': '16px',
        'stack-sm': '8px',
        'margin-desktop': '40px',
        'base': '4px',
        'gutter': '24px',
        'container-max': '1280px',
        'section-padding-v': '120px',
        'section-padding-v-mobile': '64px',
      },
      fontFamily: {
        'label-md': ['Inter'],
        'headline-md': ['Plus Jakarta Sans'],
        'body-sm': ['Inter'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'code-md': ['JetBrains Mono'],
        'body-md': ['Inter'],
        'display-lg': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'body-lg': ['Inter'],
        'display-xl-mobile': ['Plus Jakarta Sans'],
        'display-xl': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'code-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-xl-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-xl': ['72px', { lineHeight: '80px', letterSpacing: '-0.04em', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
}
